### PR TITLE
readme: fix code example, obj.thing -> value.thing

### PR DESCRIPTION
**Pull request by ralphtheninja**
Closes https://github.com/Level/memdown/issues/127

### CODE REVIEW

**Comment by ralphtheninja** [comment]
@vweevers Time for `v2.0.0` after this? Or do you want to include anything else?

**Comment by vweevers** [comment]
High time! :)

**Comment by ralphtheninja** [comment]
> High time! :)

I'll let you do the honors ;)

**Comment by vweevers** [comment]
2.0.0 🎈

**Pull request merged**
