### PR TITLE
Use immediate in browsers, setImmediate in Node

### PR DESCRIPTION
**Pull request by nolanlawson**
See https://github.com/Level/memdown/pull/59#issuecomment-261004755 for backstory.

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
👍

**Comment by juliangruber** [comment]
i think this can be simplified by removing `immediate-browser.js` and having `"./immediate.js": "immediate"` in the package.json?

**Comment by nolanlawson** [comment]
@juliangruber The reason I don't do that is that that pattern breaks in Webpack and Rollup. Or at least it used to. So I don't trust it anymore.

**Comment by juliangruber** [comment]
> @juliangruber The reason I don't do that is that that pattern breaks in Webpack and Rollup. Or at least it used to. So I don't trust it anymore.

Meh, ok!

**Pull request merged**
