### PR TITLE
Tweak Readme

### PR DESCRIPTION
**Pull request by ralphtheninja**
Closes https://github.com/Level/memdown/issues/95

Will squash this.

### CODE REVIEW

**Comment by ralphtheninja** [comment]
Rebasing this onto latest `v2`

**Comment by vweevers** [comment]
This also closes #108, right?

**Comment by ralphtheninja** [comment]
> This also closes #108, right?

Oh yes it does, I thought `.travis.yml` had to be updated but it already has removed `0.12`.

**Comment by vweevers** [comment]
Yea it got a bit messy with all the changes here :)

**Comment by vweevers** [comment]
Another random failure, restarting the build.

**Pull request merged**
