### PR TITLE
Rename iterator#_end to fix conflict with abstract-leveldown

### PR DESCRIPTION
**Pull request by vweevers**
See https://github.com/Level/memdown/issues/131#issuecomment-364458367.

### CODE REVIEW

**Comment by vweevers** [comment]
Sauce Labs is failing. Really hoped we were done with that.

**Comment by ralphtheninja** [comment]
> Sauce Labs is failing. Really hoped we were done with that.

Gah.

**Comment by vweevers** [comment]
The cause (shown in the Sauce Labs dashboard on [multiple](https://saucelabs.com/beta/tests/1d76d624f03940f99503635a9056640c/metadata) [jobs](https://saucelabs.com/beta/tests/0b4f96d86f5b490484e6999c0b784b3d/metadata)):

> Your test errored. You've exceeded your Sauce Labs concurrency limit. This test was throttled and ultimately timed out waiting for a free slot to run. You can upgrade your account for higher-concurrency at https://saucelabs.com/pricing

As well as:

> Your test errored. Test exceeded maximum duration after 1800 seconds

We have a limit of 5 concurrent builds configured in Travis, and a limit of 5 concurrent browsers per build (via zuul's  `--concurrency` option). I guess that means 5x5 in total.

I'm gonna cancel all queued Sauce Labs jobs, and try setting both limits to 1.

**Comment by vweevers** [comment]
I'm also enabling Travis' auto-cancellation of PR builds.

**Comment by ralphtheninja** [comment]
yak-shaving

**Comment by vweevers** [comment]
By downgrading android to 6.0 and setting concurrency limits to 1, everything works again.

I'm rebasing.

**Comment by vweevers** [comment]
Build time has increased to 16 minutes (~10 before), that's acceptable.

**Comment by ralphtheninja** [comment]
> Build time has increased to 16 minutes (~10 before), that's acceptable.

I'd rather have it working than being unreliable.

**Comment by vweevers** [comment]
Good to merge? (don't squash this one)

**Pull request merged**
