### PR TITLE
feat(typings): add initial typings

### PR DESCRIPTION
**Pull request by MeirionHughes**

### CODE REVIEW

**Comment by ralphtheninja** [comment]
@MeirionHughes I think the browser tests fail because you are doing an external PR, push up the `typings` branch to `upstream` instead of your own fork.

**Comment by MeirionHughes** [comment]
done - do you want me to make a new pr from `typings` -> `master`

**Comment by ralphtheninja** [comment]
> done - do you want me to make a new pr from typings -> master

Sure, it shouldn't really matter with your changes, but lets try to be thorough :)

**Comment by MeirionHughes** [comment]
ahh... github is actually smart enough to know this commit (id) from my fork is the same as the one in the typings branch (memdown)

image

**Pull request closed without merging**
