### PR TITLE
chore(package): unlock abstract-leveldown dep

### PR DESCRIPTION
**Pull request by MeirionHughes**

### CODE REVIEW

**Comment by ralphtheninja** [comment]
@vweevers Added you as owner on npm so you can publish. Would be nice with a new memdown version now :wink:

**Comment by vweevers** [comment]
@ralphtheninja does the introduction of `Buffer.from()` and `alloc()` warrant more than a patch release? Not sure because the use of `safe-buffer` should mean nothing breaks.

**Comment by juliangruber** [comment]
patch should be safe

**Comment by vweevers** [comment]
1.4.1

**Comment by MeirionHughes** [comment]
That did it; my local fork of `levelup` is passing its tests again - going to PR to restore.

**Pull request merged**
