### PR TITLE
Update dependencies and remove rimraf

### LINKED ISSUE #115: Update and cleanup dependencies
- [x] Tilde for dependencies
- [x] Caret for devDependencies
- [x] Update `ts-node`

### PR DESCRIPTION
**Pull request by vweevers**
Closes #115 and #114.

### CODE REVIEW

**Comment by vweevers** [comment]
Do not merge. I see now why we need `rimraf` as a dependency: for node tests.

**Comment by ralphtheninja** [comment]
Why is this a problem for node 4 only? Because dedup functionality in npm etc?

**Comment by vweevers** [comment]
> Why is this a problem for node 4 only? Because dedup functionality in npm etc?

Probably, yea.

**Comment by vweevers** [comment]
Restored rimraf and rebased.

**Pull request merged**
