### PR TITLE
feat(typings): add initial typings

### PR DESCRIPTION
**Pull request by MeirionHughes**

### CODE REVIEW

**Comment by ralphtheninja** [comment]
@MeirionHughes I take it, it's working well on your end :)

**Comment by MeirionHughes** [comment]
@ralphtheninja yes, after I have a _fair_ amount of linking going on, but it comes through: 

image

**Comment by ralphtheninja** [comment]
Maybe https://github.com/feross/zelda can help you out? I haven't tried it myself yet.

**Comment by ralphtheninja** [comment]
1.3.0

**Comment by MeirionHughes** [comment]
hmm... the looks like npm publish ignored the file

**Comment by ralphtheninja** [comment]
@MeirionHughes Yes *sighs*. It seems that if a module is using `files` property, then _all_ files have to be included there, if you use a newer version of npm.

**Comment by MeirionHughes** [comment]
I didn't notice sorry, leveldown, hyper, and rocksdb don't have a `files` property on package.json. :/

**Comment by ralphtheninja** [comment]
@MeirionHughes I didn't notice it either, no worries.

**Pull request merged**
